### ISSUE TITLE
A question about class based components

### ISSUE THREAD

**Issue by 96312** [prof3ssorSt3v3/react-2021-series#1]
Hey Steve, I am finding your new react playlist fairly easy to follow along and learn from. While going through  episodes 3-5, I started wondering about when to use class-based OR function-based components.

> FWIW I'm also following the official react documentation along with the videos. 

This page on [State and Lifecycle](https://reactjs.org/docs/state-and-lifecycle.html) introduces the process of converting function based components to class based ones to facilitate handling state. Unfortunately, as a newbie to react - I didn't completely follow their `clock()` example. My questions are:

1. Is there a criteria besides state that helps us decide which component 'style' to use?
2. Google says there's something called hooks that renders the class based approach redundant for handling state (I'm yet to start Ep. 6). If that's true...why do you think are the official docs introducing classes in a lesson under their `Main Concepts` section?
3. Generally speaking, is the class based approach still a useful thing to learn in 2021? Especially for people who are not going to be dealing with legacy react codebases?

Thanks for your time and these wonderful lessons and follow-ups.

Joe.

**Comment by prof3ssorSt3v3** [comment]
A few years ago I made a React series using classes - https://www.youtube.com/watch?v=vTFVg6I2wNI&list=PLyuRouwmQCjm1N4jlJ7b3WWjDA8MjfDbg - in which everything was class-based components. The class-based components use the lifecycle methods and have the setState method for managing a single state object per component.
Over the last year or so, the function-based approach has become the norm, the standard. Hooks allow us to do everything we need in React without having to work with the classes, `this`, and the complexity that came with the class approach. 
We are back to using functions solely.
That is why I am making this series. 
React still supports both. They are gradually updating their documentation to show both ways.
I am teaching a course with React currently in College. I have spent about 15 minutes talking about the class based approach versus hours talking about function-based components.
If I were learning React now I wouldn't bother with the classes.

**Comment by 96312** [comment]
Oh I see, that makes perfect sense. Despite not knowing these reasons, I had instinctively gravitated towards the function-based approach while trying out example code-snippets locally.

Going through the docs will now be much more productive. Looking forward to the rest of the series. Thank you for the follow-up and answering the questions, I appreciate you!
